/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoraampli;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cajaTexto = new javax.swing.JTextField();
        jButtonC = new javax.swing.JButton();
        jButtonDiv = new javax.swing.JButton();
        jButtonMult = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButtonIgual = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonMas = new javax.swing.JButton();
        jButtonMenos = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonComa = new javax.swing.JButton();
        jButtonCierraP = new javax.swing.JButton();
        jButtonAbreP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cajaTexto.setEditable(false);

        jButtonC.setText("CE");
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });

        jButtonDiv.setText("/");
        jButtonDiv.setEnabled(false);
        jButtonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivActionPerformed(evt);
            }
        });

        jButtonMult.setText("*");
        jButtonMult.setEnabled(false);
        jButtonMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultActionPerformed(evt);
            }
        });

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButtonIgual.setText("=");
        jButtonIgual.setEnabled(false);
        jButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgualActionPerformed(evt);
            }
        });

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonMas.setText("+");
        jButtonMas.setEnabled(false);
        jButtonMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasActionPerformed(evt);
            }
        });

        jButtonMenos.setText("-");
        jButtonMenos.setEnabled(false);
        jButtonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("C");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButtonComa.setText(",");
        jButtonComa.setEnabled(false);
        jButtonComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComaActionPerformed(evt);
            }
        });

        jButtonCierraP.setText(")");
        jButtonCierraP.setEnabled(false);
        jButtonCierraP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCierraPActionPerformed(evt);
            }
        });

        jButtonAbreP.setText("(");
        jButtonAbreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrePActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonComa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAbreP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCierraP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(cajaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAbreP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCierraP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonComa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonMult, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int parentAbiertos=0;
    int parentCerrados=0;
    List listaOp=new ArrayList();
    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        cajaTexto.setText(cajaTexto.getText()+0);
        jButtonComa.setEnabled(true);
        //jButtonAbreP.setEnabled(true);
        jButtonCierraP.setEnabled(true);
        jButtonDiv.setEnabled(true);
        jButtonMas.setEnabled(true);
        jButtonMenos.setEnabled(true);
        jButtonMult.setEnabled(true);
        jButtonIgual.setEnabled(true);
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComaActionPerformed
        cajaTexto.setText(cajaTexto.getText()+".");
        jButtonComa.setEnabled(false);
        jButtonAbreP.setEnabled(false);
        jButtonCierraP.setEnabled(false);
        jButtonDiv.setEnabled(false);
        jButtonMas.setEnabled(false);
        jButtonMenos.setEnabled(false);
        jButtonMult.setEnabled(false);
        jButtonIgual.setEnabled(false);
    }//GEN-LAST:event_jButtonComaActionPerformed

    private void jButtonMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultActionPerformed
        cajaTexto.setText(cajaTexto.getText()+"*");
         jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButton0.setEnabled(true);
        jButtonComa.setEnabled(false);
        jButtonAbreP.setEnabled(true);
        jButtonCierraP.setEnabled(false);
        jButtonDiv.setEnabled(false);
        jButtonMas.setEnabled(false);
        jButtonMenos.setEnabled(false);
        jButtonMult.setEnabled(false);
        jButtonIgual.setEnabled(false);
    }//GEN-LAST:event_jButtonMultActionPerformed

    private void jButtonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivActionPerformed
        cajaTexto.setText(cajaTexto.getText()+"/");
         jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButton0.setEnabled(true);
        jButtonComa.setEnabled(false);
        jButtonAbreP.setEnabled(true);
        jButtonCierraP.setEnabled(false);
        jButtonDiv.setEnabled(false);
        jButtonMas.setEnabled(false);
        jButtonMenos.setEnabled(false);
        jButtonMult.setEnabled(false);
        jButtonIgual.setEnabled(false);
    }//GEN-LAST:event_jButtonDivActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cajaTexto.setText(cajaTexto.getText()+1);
        jButtonComa.setEnabled(true);
        jButtonAbreP.setEnabled(false);
        jButtonCierraP.setEnabled(true);
        jButtonDiv.setEnabled(true);
        jButtonMas.setEnabled(true);
        jButtonMenos.setEnabled(true);
        jButtonMult.setEnabled(true);
        jButtonIgual.setEnabled(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cajaTexto.setText(cajaTexto.getText()+2);
        jButtonComa.setEnabled(true);
        jButtonAbreP.setEnabled(false);
        jButtonCierraP.setEnabled(true);
        jButtonDiv.setEnabled(true);
        jButtonMas.setEnabled(true);
        jButtonMenos.setEnabled(true);
        jButtonMult.setEnabled(true);
        jButtonIgual.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        cajaTexto.setText(cajaTexto.getText()+3);
        jButtonComa.setEnabled(true);
        jButtonAbreP.setEnabled(false);
        jButtonCierraP.setEnabled(true);
        jButtonDiv.setEnabled(true);
        jButtonMas.setEnabled(true);
        jButtonMenos.setEnabled(true);
        jButtonMult.setEnabled(true);
        jButtonIgual.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasActionPerformed
        // TODO add your handling code here:
        cajaTexto.setText(cajaTexto.getText()+"+");
         jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButton0.setEnabled(true);
        jButtonComa.setEnabled(false);
        jButtonAbreP.setEnabled(true);
        jButtonCierraP.setEnabled(false);
        jButtonDiv.setEnabled(false);
        jButtonMas.setEnabled(false);
        jButtonMenos.setEnabled(false);
        jButtonMult.setEnabled(false);
        jButtonIgual.setEnabled(false);
    }//GEN-LAST:event_jButtonMasActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        cajaTexto.setText(cajaTexto.getText()+6);
        jButtonComa.setEnabled(true);
        jButtonAbreP.setEnabled(false);
        jButtonCierraP.setEnabled(true);
        jButtonDiv.setEnabled(true);
        jButtonMas.setEnabled(true);
        jButtonMenos.setEnabled(true);
        jButtonMult.setEnabled(true);
        jButtonIgual.setEnabled(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        cajaTexto.setText(cajaTexto.getText()+5);
        jButtonComa.setEnabled(true);
        jButtonAbreP.setEnabled(false);
        jButtonCierraP.setEnabled(true);
        jButtonDiv.setEnabled(true);
        jButtonMas.setEnabled(true);
        jButtonMenos.setEnabled(true);
        jButtonMult.setEnabled(true);
        jButtonIgual.setEnabled(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        cajaTexto.setText(cajaTexto.getText()+4);
        jButtonComa.setEnabled(true);
        jButtonAbreP.setEnabled(false);
        jButtonCierraP.setEnabled(true);
        jButtonDiv.setEnabled(true);
        jButtonMas.setEnabled(true);
        jButtonMenos.setEnabled(true);
        jButtonMult.setEnabled(true);
        jButtonIgual.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosActionPerformed
        // TODO add your handling code here:
         jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButton0.setEnabled(true);
        cajaTexto.setText(cajaTexto.getText()+"-");
        jButtonComa.setEnabled(false);
        jButtonAbreP.setEnabled(true);
        jButtonCierraP.setEnabled(false);
        jButtonDiv.setEnabled(false);
        jButtonMas.setEnabled(false);
        jButtonMenos.setEnabled(false);
        jButtonMult.setEnabled(false);
        jButtonIgual.setEnabled(false);
    }//GEN-LAST:event_jButtonMenosActionPerformed

    private void jButtonCierraPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCierraPActionPerformed
        // TODO add your handling code here:
        parentCerrados++;
        
        cajaTexto.setText(cajaTexto.getText()+")");
        jButtonComa.setEnabled(false);
        jButtonAbreP.setEnabled(false);
       // jButtonCierraP.setEnabled(false);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton9.setEnabled(false);
        jButton0.setEnabled(false);
        // jButtonDiv.setEnabled(false);
        //jButtonMas.setEnabled(false);
        //jButtonMenos.setEnabled(false);
        //jButtonMult.setEnabled(false);
        //jButtonIgual.setEnabled(false);
    }//GEN-LAST:event_jButtonCierraPActionPerformed

    private void jButtonAbrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrePActionPerformed
        // TODO add your handling code here:
         parentAbiertos++;
        cajaTexto.setText(cajaTexto.getText()+"(");
        jButtonComa.setEnabled(false);
        //jButtonAbreP.setEnabled(false);
        jButtonCierraP.setEnabled(false);
        jButtonDiv.setEnabled(false);
        jButtonMas.setEnabled(false);
        jButtonMenos.setEnabled(true);
        jButtonMult.setEnabled(false);
        jButtonIgual.setEnabled(false);
         jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButton0.setEnabled(true);
    }//GEN-LAST:event_jButtonAbrePActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        // TODO add your handling code here:
        String aux;
        aux=cajaTexto.getText();
        if(aux.length()>0)
        cajaTexto.setText( aux.substring(0, aux.length()-1) );
        else
        
        jButtonComa.setEnabled(true);
        jButtonAbreP.setEnabled(true);
        jButtonCierraP.setEnabled(true);
        jButtonDiv.setEnabled(true);
        jButtonMas.setEnabled(true);
        jButtonMenos.setEnabled(true);
        jButtonMult.setEnabled(true);
        jButtonIgual.setEnabled(true);
         jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButton0.setEnabled(true);
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        cajaTexto.setText("");
        jButtonComa.setEnabled(true);
        jButtonAbreP.setEnabled(true);
        jButtonCierraP.setEnabled(true);
        jButtonDiv.setEnabled(true);
        jButtonMas.setEnabled(true);
        jButtonMenos.setEnabled(true);
        jButtonMult.setEnabled(true);
        jButtonIgual.setEnabled(true);
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        cajaTexto.setText(cajaTexto.getText()+7);
        jButtonComa.setEnabled(true);
        jButtonAbreP.setEnabled(false);
        jButtonCierraP.setEnabled(true);
        jButtonDiv.setEnabled(true);
        jButtonMas.setEnabled(true);
        jButtonMenos.setEnabled(true);
        jButtonMult.setEnabled(true);
        jButtonIgual.setEnabled(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        cajaTexto.setText(cajaTexto.getText()+8);
        jButtonComa.setEnabled(true);
        jButtonAbreP.setEnabled(false);
        jButtonCierraP.setEnabled(true);
        jButtonDiv.setEnabled(true);
        jButtonMas.setEnabled(true);
        jButtonMenos.setEnabled(true);
        jButtonMult.setEnabled(true);
        jButtonIgual.setEnabled(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        cajaTexto.setText(cajaTexto.getText()+9);
        jButtonComa.setEnabled(true);
        jButtonAbreP.setEnabled(false);
        jButtonCierraP.setEnabled(true);
        jButtonDiv.setEnabled(true);
        jButtonMas.setEnabled(true);
        jButtonMenos.setEnabled(true);
        jButtonMult.setEnabled(true);
        jButtonIgual.setEnabled(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualActionPerformed
        // TODO add your handling code here:
        if(parentAbiertos!=parentCerrados){
            JOptionPane.showOptionDialog(this, "LOS PARENTESIS NO ESTAN BIEN.\n   VUELVA A INTENTARLO", "ERROR", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" Aceptar "},"Aceptar");
          cajaTexto.setText("");
        }else{
            Expresion expresion = new Expresion(cajaTexto.getText());
            try {
                cajaTexto.setText(String.valueOf(expresion.compile()));
                // cajaTexto.setText(String.valueOf(result));
            } catch (Exception ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cajaTexto;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAbreP;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonCierraP;
    private javax.swing.JButton jButtonComa;
    private javax.swing.JButton jButtonDiv;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonMas;
    private javax.swing.JButton jButtonMenos;
    private javax.swing.JButton jButtonMult;
    // End of variables declaration//GEN-END:variables
}
